spring.application.name=03_microservicio_crud_reactivo
spring.main.web-application-type=reactive
server.port=9001
clave=ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
spring.r2dbc.url=r2dbc:mysql://127.0.0.1:3306/
spring.r2dbc.name=springsecurity
spring.r2dbc.username=root
spring.r2dbc.password=
