spring.application.name=10_microservicio_crud_productos_reactivo_mongodb
server.port=8000
spring.mongodb.uri=mongodb://localhost:27017/products
spring.mongodb.database=products
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG